[package]
name = "gui"
version = "0.1.0"
authors = ["Mario Ortiz Manero <marioortizmanero@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
simplelog = "0.8.0"
gtk = "0.9.0"
core = { path = "../core" }
