[package]
name = "config_macro"
version = "0.1.0"
authors = ["Mario Ortiz Manero <marioortizmanero@gmail.com>"]
edition = "2018"

[dependencies]
config_macro_derive = { path = "config_macro_derive" }
